package Acme::CPANLists::Import::PerlAdvent::2014_12_15;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2014/2014-12-15.html] (retrieved on 2016-11-06). Visit the URL for the full contents.",entries=>[{module=>"CPAN::DistnameInfo"},{module=>"ExtUtils::MakeMaker"},{module=>"MetaCPAN::Client"},{module=>"Path::Iterator::Rule"},{module=>"URI::Title"}],summary=>"Modules mentioned in Perl Advent Calendar 2014 (day 15)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2014 (day 15)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2014/2014-12-15.html> (retrieved on 2016-11-06). Visit the URL for the full contents.

