package Acme::CPANLists::Import::PerlAdvent::2014_12_06;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2014/2014-12-06.html] (retrieved on 2016-11-06). Visit the URL for the full contents.",entries=>[{module=>"DBI"},{module=>"Test::DatabaseRow"},{module=>"Test::More"}],summary=>"Modules mentioned in Perl Advent Calendar 2014 (day 06)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2014 (day 06)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2014/2014-12-06.html> (retrieved on 2016-11-06). Visit the URL for the full contents.

