package Acme::CPANLists::Import::PerlAdvent::2014_12_22;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2014/2014-12-22.html] (retrieved on 2016-11-06). Visit the URL for the full contents.",entries=>[{module=>"Moose"},{module=>"Path::Router"},{module=>"Plack"},{module=>"Plack::App::Path::Router"},{module=>"Plack::App::Path::Router::Custom"}],summary=>"Modules mentioned in Perl Advent Calendar 2014 (day 22)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2014 (day 22)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2014/2014-12-22.html> (retrieved on 2016-11-06). Visit the URL for the full contents.

