package Acme::CPANLists::Import::PerlAdvent::2014_12_07;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2014/2014-12-07.html] (retrieved on 2016-11-06). Visit the URL for the full contents.",entries=>[{module=>"Time::Limit"}],summary=>"Modules mentioned in Perl Advent Calendar 2014 (day 07)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2014 (day 07)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2014/2014-12-07.html> (retrieved on 2016-11-06). Visit the URL for the full contents.

