package Acme::CPANLists::Import::PerlAdvent::2014_12_16;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2014/2014-12-16.html] (retrieved on 2016-11-06). Visit the URL for the full contents.",entries=>[{module=>"Code::TidyAll"},{module=>"Code::TidyAll::Plugin::CSSUnminifier"},{module=>"Code::TidyAll::Plugin::Go"},{module=>"Code::TidyAll::Plugin::JSBeautify"},{module=>"Code::TidyAll::Plugin::JSHint"},{module=>"Code::TidyAll::Plugin::JSLint"},{module=>"Code::TidyAll::Plugin::JSON"},{module=>"Code::TidyAll::Plugin::MasonTidy"},{module=>"Code::TidyAll::Plugin::PHPCodeSniffer"},{module=>"Code::TidyAll::Plugin::PerlCritic"},{module=>"Code::TidyAll::Plugin::PerlTidy"},{module=>"Code::TidyAll::Plugin::PodChecker"},{module=>"Code::TidyAll::Plugin::PodSpell"},{module=>"Code::TidyAll::Plugin::SVG"},{module=>"Code::TidyAll::Plugin::SortLines"},{module=>"Code::TidyAll::Plugin::SortLines::Naturally"},{module=>"Code::TidyAll::Plugin::UniqueLines"},{module=>"File::Zglob"},{module=>"Perl::Tidy"}],summary=>"Modules mentioned in Perl Advent Calendar 2014 (day 16)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2014 (day 16)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2014/2014-12-16.html> (retrieved on 2016-11-06). Visit the URL for the full contents.

