package Acme::CPANLists::Import::PerlAdvent::2014_12_17;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2014/2014-12-17.html] (retrieved on 2016-11-06). Visit the URL for the full contents.",entries=>[{module=>"BPM::Engine"},{module=>"DBD::SQLite"},{module=>"DBI"},{module=>"Devel::Monitor"},{module=>"HTTP::Tiny"},{module=>"IO::Socket::SSL"},{module=>"Kavorka"},{module=>"LWP"},{module=>"Moo"},{module=>"Moose"},{module=>"Mouse"},{module=>"Sereal"},{module=>"Storable"},{module=>"Test::LeakTrace"},{module=>"Test::Requires"},{module=>"Test::Requires::Env"},{module=>"Test::RequiresInternet"},{module=>"Text::Xslate"},{module=>"Tiffany"},{module=>"WWW::Mechanize"},{module=>"ZeroMQ"},{module=>"namespace::autoclean"}],summary=>"Modules mentioned in Perl Advent Calendar 2014 (day 17)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2014 (day 17)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2014/2014-12-17.html> (retrieved on 2016-11-06). Visit the URL for the full contents.

